CREATE TABLE [PRODUTOS] 
(
	[PRODUTO] NVARCHAR(255),
	[COMISSAO_AFILIADO] DECIMAL(3,2),
	[TIPO] NVARCHAR(15), 
	[COMISSAO_LL_EM_COPRODUCAO] DECIMAL(3,2), 
	[COPRODUTOR] NVARCHAR(255), 
	[PROJETO] NVARCHAR(20)
);
	
CREATE TABLE [CONTROLE_VENDAS]
(
	[PRODUTO] [nvarchar](255) NULL,
	[PRODUTOR] [nvarchar](255) NULL,
	[AFILIADO] [nvarchar](255) NULL,
	[TRANSACAO] [nvarchar](255) NOT NULL,
	[VALOR_BRUTO_ORIGINAL] DECIMAL(17,10) NULL,
	[VALOR_BRUTO_REAL] DECIMAL(17,10) NULL,
	[TAXA_CAMBIO] DECIMAL(12,10) NULL,
	[VALOR_LIQUIDO_REAL] DECIMAL(17,10) NULL,
	[RECORRENCIA] [int] NULL,
	[FORMA_PAGAMENTO] [nvarchar](255) NULL,
	[DATA_VENDA] [datetime] NULL,
	[DATA_CONFIRMACAO] [datetime] NULL,
	[CLIENTE] [nvarchar](255) NULL,
	[DOCUMENTO] [nvarchar](255) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[PAIS] [nvarchar](255) NULL,
	[CODIGO_OFERTA] [nvarchar](255) NULL
	 CONSTRAINT [PK_CONTROLE_VENDAS] PRIMARY KEY CLUSTERED 
	(
	[TRANSACAO] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY];

CREATE TABLE [PROC_TEMP]
(
	[PRODUTO] [nvarchar](255) NULL,
	[PRODUTOR] [nvarchar](255) NULL,
	[AFILIADO] [nvarchar](255) NULL,
	[TRANSACAO] [nvarchar](255) NOT NULL,
	[VALOR_BRUTO_ORIGINAL] DECIMAL(17,10) NULL,
	[VALOR_BRUTO_REAL] DECIMAL(17,10) NULL,
	[TAXA_CAMBIO] DECIMAL(12,10) NULL,
	[VALOR_LIQUIDO_REAL] DECIMAL(17,10) NULL,
	[RECORRENCIA] [int] NULL,
	[FORMA_PAGAMENTO] [nvarchar](255) NULL,
	[DATA_VENDA] [datetime] NULL,
	[DATA_CONFIRMACAO] [datetime] NULL,
	[CLIENTE] [nvarchar](255) NULL,
	[DOCUMENTO] [nvarchar](255) NULL,
	[EMAIL] [nvarchar](255) NULL,
	[ESTADO] [nvarchar](255) NULL,
	[PAIS] [nvarchar](255) NULL,
	[CODIGO_OFERTA] [nvarchar](255) NULL,
  CONSTRAINT [PK_PROC_TEMP] PRIMARY KEY CLUSTERED 
(
	[TRANSACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];

CREATE TABLE [FIN_TEMP]
(
	[DATA_PAGAMENTO] [date] NULL,
	[COMPETENCIA] [date] NULL,
	[PLANO_CONTAS] [nvarchar](255) NULL,
	[VALOR] DECIMAL(17,10) NULL,
	[CONTA] [nvarchar](255) NULL,
	[DEPARTAMENTO] [nvarchar](255) NULL,
	[PROJETO] [nvarchar](255) NULL,
	[TRANSACAO] [nvarchar](255) NULL,
	[CAMBIO] DECIMAL(12,10) NULL,
	[VALOR_DOLAR] [float] NULL
);

CREATE TABLE [FINANCEIRO]
(
	[DATA_PAGAMENTO] [date] NULL,
	[COMPETENCIA] [date] NULL,
	[PLANO_CONTAS] [nvarchar](255) NULL,
	[VALOR] DECIMAL(17,10) NULL,
	[CONTA] [nvarchar](255) NULL,
	[DEPARTAMENTO] [nvarchar](255) NULL,
	[PROJETO] [nvarchar](255) NULL,
	[TRANSACAO] [nvarchar](255) NULL,
	[CAMBIO] DECIMAL(12,10) NULL,
	[VALOR_DOLAR] [float] NULL
);

CREATE TABLE [STATUS]
(
	[TRANSACAO] [nvarchar](255) NULL,
	[STATUS] [nvarchar](255) NULL,
	[DATA_INICIAL] [datetime] NULL,
	[DATA_FINAL] [datetime] NULL
);

CREATE TABLE [STATUS_TEMP]
(
	[TRANSACAO] [nvarchar](255) NULL,
	[STATUS] [nvarchar](255) NULL,
	[DATA_INICIAL] [datetime] NULL,
	[DATA_FINAL] [datetime] NULL
);